version: '3.7'

services:
  ca.bc-coop.bclan:
    container_name: ca-bclan-network-it
    image: smartbcity/commune-sandbox-ca:latest
    networks:
      - bclannet-it

  orderer.bclan:
    container_name: orderer-network-it
    image: smartbcity/commune-sandbox-orderer:latest
    networks:
      - bclannet-it

  peer0.bc-coop.bclan:
    container_name: peer0-bclan-network-it
    image: smartbcity/commune-sandbox-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=bclannet-it
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
    networks:
      - bclannet-it
    depends_on:
      - orderer.bclan

  cli-init.bc-coop.bclan:
    container_name: cli-init-bclan-network-it
    image: smartbcity/commune-sandbox-cli:latest
    command: /opt/commune-sandbox/util/init.sh
    networks:
      - bclannet-it
    depends_on:
      - peer0.bc-coop.bclan

  coop-rest-java:
    container_name: coop-rest-bclan-network-it
    image: smartbcity/commune-sandbox-ssm-rest:latest
    ports:
      - 9090:9090
    networks:
      - bclannet-it

networks:
  bclannet-it:
    name: bclannet-it
